name: find-and-split
description: Find and split files with GitHub Actions.
author: remarkablemark

inputs:
  chunk:
    description: The chunk as a fraction (e.g., 1/2).
    required: true
  delimiter:
    description: The delimiter.
    default: ' '
  directory:
    description: The directory.
    default: .
  pattern:
    description: 'The filename pattern (e.g., *.txt).'
    required: true

outputs:
  files:
    description: The list of files.
    value: ${{ steps.find-and-split.outputs.files }}

runs:
  using: composite
  steps:
    - name: Find and split files
      id: find-and-split
      shell: bash
      run: |
        CHUNK_NUMBER=$(echo ${{ inputs.chunk }} | cut -d/ -f1)
        CHUNK_INDEX=$((CHUNK_NUMBER - 1))
        CHUNK_TOTAL=$(echo ${{ inputs.chunk }} | cut -d/ -f2)
        PREFIX=find_and_split_${{ github.run_id }}_
        FILE=$RUNNER_TEMP/$PREFIX

        find ${{ inputs.directory }} -type f -name ${{ inputs.pattern }} | sort > $FILE

        FILES_TOTAL=$(wc -l < $FILE | xargs)
        LINES=$(( (FILES_TOTAL + 1) / CHUNK_TOTAL ))
        MAX_DIGITS=3

        if [[ $FILES_TOTAL == 0 ]]; then
          echo 'No files found. Check your inputs:'
          echo '- pattern: ${{ inputs.pattern }}'
          echo '- directory: ${{ inputs.directory }}'
          exit 1
        fi

        cd $RUNNER_TEMP
        split -d -a $MAX_DIGITS -l $LINES $FILE $PREFIX

        FILES=$(tr '\n' '${{ inputs.delimiter }}' < "$PREFIX$(printf "%0${MAX_DIGITS}d" $CHUNK_INDEX)")
        EOF=EOF_FIND_AND_SPLIT_$(openssl rand -hex 12)

        {
          echo "files<<$EOF"
          echo "$FILES"
          echo $EOF
        } >> "$GITHUB_OUTPUT"

branding:
  icon: scissors
  color: yellow
