name: commitlint
on: [push, pull_request]

permissions: read-all

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: remarkablemark/commitlint@v1
