name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and split (0/1)
        uses: ./
        with:
          chunk: 0/1
          pattern: '*.invalid'
        continue-on-error: true

      - name: Find and split (1/2)
        uses: ./
        id: test1
        with:
          chunk: 1/2
          pattern: '*.spec'

      - name: Assert files (1/2)
        shell: bash
        run: |
          actual='${{ steps.test1.outputs.files }}'
          expected='./test/1.spec ./test/2.spec '
          if [[ "$actual" != "$expected" ]]; then
            echo 'Files do not match'
            exit 1
          fi

      - name: Find and split with directory (2/2)
        uses: ./
        id: test2
        with:
          chunk: 2/2
          directory: test
          pattern: '*.spec'

      - name: Assert files with directory (2/2)
        shell: bash
        run: |
          actual='${{ steps.test2.outputs.files }}'
          expected='test/3.spec '
          if [[ "$actual" != "$expected" ]]; then
            echo 'Files do not match'
            exit 1
          fi

      - name: Find and split with delimiter (1/2)
        uses: ./
        id: test3
        with:
          chunk: 1/2
          delimiter: '\n'
          directory: test
          pattern: '*.spec'

      - name: Assert files with delimiter (1/2)
        shell: bash
        run: |
          cat <<EOF > actual
          ${{ steps.test3.outputs.files }}
          EOF

          cat <<EOF > expected
          test/1.spec
          test/2.spec
          EOF

          if ! cmp actual expected; then
            diff actual expected
            exit 1
          fi
