name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and split (1/2)
        uses: ./
        id: test1
        with:
          pattern: '*.spec'
          chunk: 1/2

      - name: Assert files (1/2)
        shell: bash
        run: |
          if [[ '${{ steps.test1.outputs.files }}' != './test/1.spec ./test/2.spec ' ]]; then
            echo 'Files do not match'
            exit 1
          fi

      - name: Find and split with directory (2/2)
        uses: ./
        id: test2
        with:
          directory: test
          pattern: '*.spec'
          chunk: 2/2

      - name: Assert files (2/2)
        shell: bash
        run: |
          if [[ '${{ steps.test2.outputs.files }}' != 'test/3.spec ' ]]; then
            echo 'Files do not match'
            exit 1
          fi
